---

- name: Stop services
  service:
    name: "{{ item }}"
    state: stopped
  loop:
    - apt-daily
    - apt-daily.timer
    - apt-daily-upgrade
    - apt-daily-upgrade.timer

- name: Unlock apt
  file:
    path: /var/lib/apt/lists/lock
    state: absent

- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    autoremove: yes
    autoclean: yes