---

- name: Include play for Debian Like
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Include play for RedHat Like
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"